import type { District, SenateRace, NationalOverview, SocialSignal, AICommentary } from "@/types/election";

export const NATIONAL_OVERVIEW: NationalOverview = {
  houseSeats: { d: 193, r: 214, i: 0, uncalled: 28 },
  senateSeats: { d: 45, r: 51, i: 4, uncalled: 0 },
  lastUpdated: new Date().toISOString(),
};

export const HOUSE_RACES: District[] = [
  {
    id: "nc-13",
    state: "North Carolina",
    stateAbbr: "NC",
    districtNumber: 13,
    chamber: "house",
    name: "NC-13",
    raceStatus: "toss-up",
    trending: "r",
    totalPrecincts: 847,
    reportingPrecincts: 0,
    lastUpdated: new Date().toISOString(),
    candidates: [
      { id: "nc13-d", name: "Jeff Jackson", party: "D", incumbent: false, votes: 0, votePercent: 0, fundsRaised: 4200000, cashOnHand: 1800000 },
      { id: "nc13-r", name: "Greg Murphy", party: "R", incumbent: true, votes: 0, votePercent: 0, fundsRaised: 3100000, cashOnHand: 920000 },
    ],
    precincts: [],
  },
  {
    id: "az-01",
    state: "Arizona",
    stateAbbr: "AZ",
    districtNumber: 1,
    chamber: "house",
    name: "AZ-01",
    raceStatus: "lean-r",
    trending: "none",
    totalPrecincts: 623,
    reportingPrecincts: 0,
    lastUpdated: new Date().toISOString(),
    candidates: [
      { id: "az1-d", name: "Amish Shah", party: "D", incumbent: false, votes: 0, votePercent: 0, fundsRaised: 2900000, cashOnHand: 740000 },
      { id: "az1-r", name: "David Schweikert", party: "R", incumbent: true, votes: 0, votePercent: 0, fundsRaised: 2400000, cashOnHand: 580000 },
    ],
    precincts: [],
  },
  {
    id: "pa-07",
    state: "Pennsylvania",
    stateAbbr: "PA",
    districtNumber: 7,
    chamber: "house",
    name: "PA-07",
    raceStatus: "lean-d",
    trending: "d",
    totalPrecincts: 901,
    reportingPrecincts: 0,
    lastUpdated: new Date().toISOString(),
    candidates: [
      { id: "pa7-d", name: "Susan Wild", party: "D", incumbent: true, votes: 0, votePercent: 0, fundsRaised: 5800000, cashOnHand: 2100000 },
      { id: "pa7-r", name: "Ryan Mackenzie", party: "R", incumbent: false, votes: 0, votePercent: 0, fundsRaised: 3300000, cashOnHand: 890000 },
    ],
    precincts: [],
  },
  {
    id: "mi-10",
    state: "Michigan",
    stateAbbr: "MI",
    districtNumber: 10,
    chamber: "house",
    name: "MI-10",
    raceStatus: "toss-up",
    trending: "none",
    totalPrecincts: 714,
    reportingPrecincts: 0,
    lastUpdated: new Date().toISOString(),
    candidates: [
      { id: "mi10-d", name: "Carl Marlinga", party: "D", incumbent: false, votes: 0, votePercent: 0, fundsRaised: 3700000, cashOnHand: 1200000 },
      { id: "mi10-r", name: "John James", party: "R", incumbent: true, votes: 0, votePercent: 0, fundsRaised: 6100000, cashOnHand: 2900000 },
    ],
    precincts: [],
  },
  {
    id: "nv-03",
    state: "Nevada",
    stateAbbr: "NV",
    districtNumber: 3,
    chamber: "house",
    name: "NV-03",
    raceStatus: "toss-up",
    trending: "d",
    totalPrecincts: 512,
    reportingPrecincts: 0,
    lastUpdated: new Date().toISOString(),
    candidates: [
      { id: "nv3-d", name: "Susie Lee", party: "D", incumbent: true, votes: 0, votePercent: 0, fundsRaised: 4400000, cashOnHand: 1700000 },
      { id: "nv3-r", name: "April Becker", party: "R", incumbent: false, votes: 0, votePercent: 0, fundsRaised: 2800000, cashOnHand: 670000 },
    ],
    precincts: [],
  },
];

export const SENATE_RACES: SenateRace[] = [
  {
    id: "az-sen",
    state: "Arizona",
    stateAbbr: "AZ",
    seatClass: 3,
    raceStatus: "toss-up",
    trending: "r",
    totalPrecincts: 2847,
    reportingPrecincts: 0,
    lastUpdated: new Date().toISOString(),
    candidates: [
      { id: "az-sen-d", name: "Ruben Gallego", party: "D", incumbent: true, fundsRaised: 24000000, cashOnHand: 9800000 },
      { id: "az-sen-r", name: "Kari Lake", party: "R", incumbent: false, fundsRaised: 18000000, cashOnHand: 4200000 },
    ],
    precincts: [],
  },
  {
    id: "mt-sen",
    state: "Montana",
    stateAbbr: "MT",
    seatClass: 2,
    raceStatus: "lean-r",
    trending: "r",
    totalPrecincts: 634,
    reportingPrecincts: 0,
    lastUpdated: new Date().toISOString(),
    candidates: [
      { id: "mt-sen-d", name: "Jon Tester", party: "D", incumbent: true, fundsRaised: 31000000, cashOnHand: 7100000 },
      { id: "mt-sen-r", name: "Tim Sheehy", party: "R", incumbent: false, fundsRaised: 22000000, cashOnHand: 5800000 },
    ],
    precincts: [],
  },
  {
    id: "pa-sen",
    state: "Pennsylvania",
    stateAbbr: "PA",
    seatClass: 3,
    raceStatus: "lean-d",
    trending: "d",
    totalPrecincts: 9127,
    reportingPrecincts: 0,
    lastUpdated: new Date().toISOString(),
    candidates: [
      { id: "pa-sen-d", name: "Bob Casey", party: "D", incumbent: true, fundsRaised: 38000000, cashOnHand: 12000000 },
      { id: "pa-sen-r", name: "Dave McCormick", party: "R", incumbent: false, fundsRaised: 29000000, cashOnHand: 8400000 },
    ],
    precincts: [],
  },
  {
    id: "nv-sen",
    state: "Nevada",
    stateAbbr: "NV",
    seatClass: 3,
    raceStatus: "toss-up",
    trending: "none",
    totalPrecincts: 1843,
    reportingPrecincts: 0,
    lastUpdated: new Date().toISOString(),
    candidates: [
      { id: "nv-sen-d", name: "Jacky Rosen", party: "D", incumbent: true, fundsRaised: 27000000, cashOnHand: 10000000 },
      { id: "nv-sen-r", name: "Sam Brown", party: "R", incumbent: false, fundsRaised: 19000000, cashOnHand: 5100000 },
    ],
    precincts: [],
  },
];

export const SOCIAL_SIGNALS: SocialSignal[] = [
  { id: "s1", platform: "twitter", text: "NC-13 is looking extremely competitive. Early mail ballots trending toward Murphy by +4 in Wake County", author: "@ElectionNerd2026", timestamp: new Date().toISOString(), sentiment: "neutral", districtId: "nc-13" },
  { id: "s2", platform: "reddit", text: "Arizona Senate race: Maricopa County reporting delays expected. Could extend night significantly.", author: "u/azpoliticswatcher", timestamp: new Date().toISOString(), sentiment: "neutral", districtId: "az-sen" },
  { id: "s3", platform: "youtube", text: "LIVE: 45,000 watching Election Gorilla cover PA-07 precinct by precinct breakdown!", author: "ElectionGorilla Live", timestamp: new Date().toISOString(), sentiment: "positive" },
  { id: "s4", platform: "twitter", text: "MI-10 is the closest race in the country right now. John James overperforming in Oakland County suburbs.", author: "@TargetedPrecinct", timestamp: new Date().toISOString(), sentiment: "neutral", districtId: "mi-10" },
  { id: "s5", platform: "reddit", text: "Nevada-3 mail ballot dumps usually drop at 10pm local time. Susie Lee historically strong there.", author: "u/nevadaelections", timestamp: new Date().toISOString(), sentiment: "neutral", districtId: "nv-03" },
];

export const AI_COMMENTARY: AICommentary[] = [
  { id: "c1", text: "NC-13 precincts are not yet reporting but historical precinct-level data shows this race could come down to fewer than 5,000 votes in Johnston County alone. Watch for those results closely.", timestamp: new Date().toISOString(), topic: "data-insight", relatedDistrictId: "nc-13" },
  { id: "c2", text: "Arizona Senate: Maricopa County accounts for 62% of total statewide vote. Any shift of even 1 point in Maricopa changes the outcome. This is the county to watch all night.", timestamp: new Date().toISOString(), topic: "data-insight", relatedDistrictId: "az-sen" },
  { id: "c3", text: "Montana Senate race is trending red but don't count out Tester yet — he's a 3-time survivor in a deep-red state and knows exactly which precincts to run up the score in.", timestamp: new Date().toISOString(), topic: "trending", relatedDistrictId: "mt-sen" },
  { id: "c4", text: "BREAKING: Pennsylvania-07 now has 3% of precincts reporting. Current margin: Wild +2.1. This is within the expected range for a Democrat lead.", timestamp: new Date().toISOString(), topic: "breaking", relatedDistrictId: "pa-07" },
];
