import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// ─── Seed Script: 10 Real 2026 Race Objects ──────────────────────────────────

async function main() {
  console.log("Seeding 10 real 2026 Race Objects...");

  const races = [
    // ── SENATE RACES ──
    {
      raceId: "2026-PA-SEN",
      cycleYear: 2026,
      raceType: "SENATE" as const,
      state: "PA",
      district: "",
      partisanLean: 0.5,
      historicalTurnout: 0.67,
      incumbentParty: "DEMOCRAT" as const,
      incumbentName: "John Fetterman",
      isOpenSeat: false,
      demPrimaryDate: new Date("2026-05-19"),
      repPrimaryDate: new Date("2026-05-19"),
      generalElectionDate: new Date("2026-11-03"),
      candidates: [
        { candidate_id: "fetterman-pa", full_name: "John Fetterman", party: "DEMOCRAT", fec_candidate_id: "S2PA00451", declared_date: "2025-01-15", website: "https://fetterman.senate.gov", status: "DECLARED" },
        { candidate_id: "mccormick-pa", full_name: "Dave McCormick", party: "REPUBLICAN", fec_candidate_id: "S2PA00469", declared_date: "2025-06-01", website: "", status: "DECLARED" },
      ],
      pollingAverages: [
        { candidate_id: "fetterman-pa", candidate_name: "John Fetterman", average_pct: 47.2, as_of_date: "2026-03-01" },
        { candidate_id: "mccormick-pa", candidate_name: "Dave McCormick", average_pct: 45.8, as_of_date: "2026-03-01" },
      ],
      pollingTrend: "SHIFTING_D" as const,
      pollingSpread: -1.4,
      coverageTier: 1,
      tierScoreRaw: 88.5,
      coverageFrequencyTarget: "DAILY" as const,
      enthusiasmIndex: 72.0,
      earnedMediaVelocity: 34.0,
      socialSentimentScore: 0.52,
      smallDollarPct: 38.0,
    },
    {
      raceId: "2026-GA-SEN",
      cycleYear: 2026,
      raceType: "SENATE" as const,
      state: "GA",
      district: "",
      partisanLean: 1.5,
      historicalTurnout: 0.63,
      incumbentParty: "DEMOCRAT" as const,
      incumbentName: "Jon Ossoff",
      isOpenSeat: false,
      demPrimaryDate: new Date("2026-05-19"),
      repPrimaryDate: new Date("2026-05-19"),
      generalElectionDate: new Date("2026-11-03"),
      candidates: [
        { candidate_id: "ossoff-ga", full_name: "Jon Ossoff", party: "DEMOCRAT", fec_candidate_id: "S2GA00388", declared_date: "2025-03-01", website: "https://ossoff.senate.gov", status: "DECLARED" },
      ],
      pollingAverages: [],
      pollingTrend: "INSUFFICIENT_DATA" as const,
      pollingSpread: 0,
      coverageTier: 1,
      tierScoreRaw: 85.0,
      coverageFrequencyTarget: "DAILY" as const,
      enthusiasmIndex: 65.0,
      earnedMediaVelocity: 28.0,
      socialSentimentScore: 0.48,
      smallDollarPct: 42.0,
    },
    {
      raceId: "2026-MI-SEN",
      cycleYear: 2026,
      raceType: "SENATE" as const,
      state: "MI",
      district: "",
      partisanLean: -0.3,
      historicalTurnout: 0.65,
      incumbentParty: "DEMOCRAT" as const,
      incumbentName: "Gary Peters",
      isOpenSeat: true,
      demPrimaryDate: new Date("2026-08-04"),
      repPrimaryDate: new Date("2026-08-04"),
      generalElectionDate: new Date("2026-11-03"),
      candidates: [],
      pollingAverages: [],
      pollingTrend: "INSUFFICIENT_DATA" as const,
      pollingSpread: 0,
      coverageTier: 1,
      tierScoreRaw: 92.0,
      coverageFrequencyTarget: "DAILY" as const,
      enthusiasmIndex: 58.0,
      earnedMediaVelocity: 22.0,
      socialSentimentScore: 0.50,
      smallDollarPct: 35.0,
    },
    {
      raceId: "2026-NC-SEN",
      cycleYear: 2026,
      raceType: "SENATE" as const,
      state: "NC",
      district: "",
      partisanLean: 3.5,
      historicalTurnout: 0.62,
      incumbentParty: "REPUBLICAN" as const,
      incumbentName: "Thom Tillis",
      isOpenSeat: false,
      demPrimaryDate: new Date("2026-05-05"),
      repPrimaryDate: new Date("2026-05-05"),
      generalElectionDate: new Date("2026-11-03"),
      candidates: [
        { candidate_id: "tillis-nc", full_name: "Thom Tillis", party: "REPUBLICAN", fec_candidate_id: "S4NC00162", declared_date: "2025-04-01", website: "", status: "DECLARED" },
      ],
      pollingAverages: [],
      pollingTrend: "STABLE" as const,
      pollingSpread: 3.0,
      coverageTier: 2,
      tierScoreRaw: 68.0,
      coverageFrequencyTarget: "TWICE_WEEKLY" as const,
      enthusiasmIndex: 42.0,
      earnedMediaVelocity: 15.0,
      socialSentimentScore: 0.44,
      smallDollarPct: 28.0,
    },
    // ── HOUSE RACES ──
    {
      raceId: "2026-CA-27-HOU",
      cycleYear: 2026,
      raceType: "HOUSE" as const,
      state: "CA",
      district: "27",
      partisanLean: -1.2,
      historicalTurnout: 0.55,
      incumbentParty: "REPUBLICAN" as const,
      incumbentName: "Mike Garcia",
      isOpenSeat: false,
      demPrimaryDate: new Date("2026-03-03"),
      repPrimaryDate: new Date("2026-03-03"),
      generalElectionDate: new Date("2026-11-03"),
      candidates: [
        { candidate_id: "garcia-ca27", full_name: "Mike Garcia", party: "REPUBLICAN", fec_candidate_id: "H0CA25148", declared_date: "2025-02-01", website: "", status: "DECLARED" },
        { candidate_id: "smith-ca27", full_name: "George Whitesides", party: "DEMOCRAT", fec_candidate_id: "H4CA27074", declared_date: "2025-05-01", website: "", status: "DECLARED" },
      ],
      pollingAverages: [
        { candidate_id: "garcia-ca27", candidate_name: "Mike Garcia", average_pct: 48.5, as_of_date: "2026-02-15" },
        { candidate_id: "smith-ca27", candidate_name: "George Whitesides", average_pct: 47.1, as_of_date: "2026-02-15" },
      ],
      pollingTrend: "VOLATILE" as const,
      pollingSpread: 1.4,
      coverageTier: 2,
      tierScoreRaw: 72.0,
      coverageFrequencyTarget: "TWICE_WEEKLY" as const,
      enthusiasmIndex: 55.0,
      earnedMediaVelocity: 18.0,
      socialSentimentScore: 0.51,
      smallDollarPct: 45.0,
    },
    {
      raceId: "2026-NY-04-HOU",
      cycleYear: 2026,
      raceType: "HOUSE" as const,
      state: "NY",
      district: "04",
      partisanLean: -4.0,
      historicalTurnout: 0.58,
      incumbentParty: "REPUBLICAN" as const,
      incumbentName: "Anthony D'Esposito",
      isOpenSeat: true,
      demPrimaryDate: new Date("2026-06-23"),
      repPrimaryDate: new Date("2026-06-23"),
      generalElectionDate: new Date("2026-11-03"),
      candidates: [],
      pollingAverages: [],
      pollingTrend: "INSUFFICIENT_DATA" as const,
      pollingSpread: 0,
      coverageTier: 2,
      tierScoreRaw: 70.0,
      coverageFrequencyTarget: "TWICE_WEEKLY" as const,
      enthusiasmIndex: 48.0,
      earnedMediaVelocity: 12.0,
      socialSentimentScore: 0.46,
      smallDollarPct: 40.0,
    },
    {
      raceId: "2026-NE-02-HOU",
      cycleYear: 2026,
      raceType: "HOUSE" as const,
      state: "NE",
      district: "02",
      partisanLean: 2.0,
      historicalTurnout: 0.61,
      incumbentParty: "REPUBLICAN" as const,
      incumbentName: "Don Bacon",
      isOpenSeat: false,
      demPrimaryDate: new Date("2026-05-12"),
      repPrimaryDate: new Date("2026-05-12"),
      generalElectionDate: new Date("2026-11-03"),
      candidates: [
        { candidate_id: "bacon-ne02", full_name: "Don Bacon", party: "REPUBLICAN", fec_candidate_id: "H6NE02101", declared_date: "2025-01-20", website: "", status: "DECLARED" },
      ],
      pollingAverages: [],
      pollingTrend: "STABLE" as const,
      pollingSpread: 2.0,
      coverageTier: 3,
      tierScoreRaw: 55.0,
      coverageFrequencyTarget: "WEEKLY" as const,
      enthusiasmIndex: 38.0,
      earnedMediaVelocity: 8.0,
      socialSentimentScore: 0.49,
      smallDollarPct: 32.0,
    },
    {
      raceId: "2026-AZ-01-HOU",
      cycleYear: 2026,
      raceType: "HOUSE" as const,
      state: "AZ",
      district: "01",
      partisanLean: 1.5,
      historicalTurnout: 0.56,
      incumbentParty: "REPUBLICAN" as const,
      incumbentName: "David Schweikert",
      isOpenSeat: false,
      demPrimaryDate: new Date("2026-08-04"),
      repPrimaryDate: new Date("2026-08-04"),
      generalElectionDate: new Date("2026-11-03"),
      candidates: [
        { candidate_id: "schweikert-az01", full_name: "David Schweikert", party: "REPUBLICAN", fec_candidate_id: "H0AZ05099", declared_date: "2025-03-01", website: "", status: "DECLARED" },
      ],
      pollingAverages: [],
      pollingTrend: "INSUFFICIENT_DATA" as const,
      pollingSpread: 0,
      coverageTier: 2,
      tierScoreRaw: 66.0,
      coverageFrequencyTarget: "TWICE_WEEKLY" as const,
      enthusiasmIndex: 44.0,
      earnedMediaVelocity: 10.0,
      socialSentimentScore: 0.47,
      smallDollarPct: 30.0,
    },
    // ── GOVERNOR RACE ──
    {
      raceId: "2026-NJ-GOV",
      cycleYear: 2026,
      raceType: "GOVERNOR" as const,
      state: "NJ",
      district: "",
      partisanLean: -6.0,
      historicalTurnout: 0.42,
      incumbentParty: "DEMOCRAT" as const,
      incumbentName: "Phil Murphy",
      isOpenSeat: true,
      demPrimaryDate: new Date("2026-06-02"),
      repPrimaryDate: new Date("2026-06-02"),
      generalElectionDate: new Date("2026-11-03"),
      candidates: [],
      pollingAverages: [],
      pollingTrend: "INSUFFICIENT_DATA" as const,
      pollingSpread: 0,
      coverageTier: 2,
      tierScoreRaw: 65.0,
      coverageFrequencyTarget: "TWICE_WEEKLY" as const,
      enthusiasmIndex: 50.0,
      earnedMediaVelocity: 20.0,
      socialSentimentScore: 0.53,
      smallDollarPct: 36.0,
    },
    // ── DOWN-BALLOT: STATE LEGISLATURE ──
    {
      raceId: "2026-VA-07-STATE-SEN",
      cycleYear: 2026,
      raceType: "STATE_SEN" as const,
      state: "VA",
      district: "07",
      partisanLean: 0.8,
      historicalTurnout: 0.35,
      incumbentParty: "REPUBLICAN" as const,
      incumbentName: "Tara Durant",
      isOpenSeat: false,
      demPrimaryDate: new Date("2026-06-09"),
      repPrimaryDate: new Date("2026-06-09"),
      generalElectionDate: new Date("2026-11-03"),
      candidates: [
        { candidate_id: "durant-va07", full_name: "Tara Durant", party: "REPUBLICAN", fec_candidate_id: "", declared_date: "2025-08-01", website: "", status: "DECLARED" },
      ],
      pollingAverages: [],
      pollingTrend: "INSUFFICIENT_DATA" as const,
      pollingSpread: 0,
      coverageTier: 4,
      tierScoreRaw: 28.0,
      coverageFrequencyTarget: "BIWEEKLY" as const,
      enthusiasmIndex: 22.0,
      earnedMediaVelocity: 3.0,
      socialSentimentScore: 0.50,
      smallDollarPct: 18.0,
    },
  ];

  for (const race of races) {
    await prisma.race.upsert({
      where: { raceId: race.raceId },
      update: race,
      create: race,
    });
    console.log(`  ✓ ${race.raceId} (Tier ${race.coverageTier})`);
  }

  console.log(`\nSeeded ${races.length} races successfully.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
